[plugin]
enabled = true
config_version = "1.1.0"

[server]
base_url = "https://www.diving-fish.com/api/maimaidxprober"
request_timeout = 30
music_cache_ttl = 300

[lxns]
enable = true
base_url = "https://maimai.lxns.net/api/v0"
asset_url = "https://assets.lxns.net"
request_timeout = 30
music_cache_ttl = 300
