# -*- coding: utf-8 -*-
"""AWMC / Yuzu 风格单曲详情与个人单曲成绩渲染。

与 ``b50_awmc_pillow.py`` 一样直接使用 Resource CN1.55 static 素材，
本次只负责 ``chart_info.png`` / ``play_info.png`` 两套模板的贴图拼接。
"""

from __future__ import annotations

import asyncio
import base64
import io
import unicodedata
import urllib.request
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw, ImageFont

from ..rating import compute_ra

ASSETS_ROOT = Path(__file__).resolve().parent.parent.parent / "assets" / "awmc_core"
COVER_ROOT = Path(__file__).resolve().parent.parent.parent / "assets" / "awmc" / "mai" / "cover"

DESIGN_CREDIT = "Designed by Yuri-YuzuChaN & BlueDeer233 | Generated by MaiBot"

_THEME_EXACT_FILES = {
    "b50.png",
    "b50_bg.png",
    "logo.png",
    "chart_info.png",
    "play_info.png",
    "ra_dx.png",
    "ra.png",
    "ra-dx.png",
    "song_bg.png",
    "info_bg.png",
}
_THEME_PREFIXES = (
    "UI_TTR_Rank_",
    "UI_CMN_DXRating_",
    "UI_CMN_DXRating_Star_",
    "UI_CHR_PlayBonus_",
)

RANK_MAP = {
    "d": "D",
    "c": "C",
    "b": "B",
    "bb": "BB",
    "bbb": "BBB",
    "a": "A",
    "aa": "AA",
    "aaa": "AAA",
    "s": "S",
    "sp": "Sp",
    "ss": "SS",
    "ssp": "SSp",
    "sss": "SSS",
    "sssp": "SSSp",
}
FC_MAP = {
    "fc": "FC",
    "fcp": "FCp",
    "fc+": "FCp",
    "ap": "AP",
    "app": "APp",
    "ap+": "APp",
}
FS_MAP = {
    "fs": "FS",
    "fsp": "FSp",
    "fs+": "FSp",
    "fsd": "FSD",
    "fdx": "FSD",
    "fsdp": "FSDp",
    "fdxp": "FSDp",
    "fdx+": "FSDp",
    "sync": "Sync",
}


def _f(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _i(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _song_id(song: dict) -> str:
    return str(song.get("id") or song.get("song_id") or song.get("music_id") or "0")


def _pic_dir(assets: Path) -> Path:
    return assets / "mai" / "pic"


def _theme_path(assets: Path, filename: str) -> Path:
    pic = _pic_dir(assets)
    mapped = "b50.png" if filename == "b50_bg.png" else filename
    themed = filename in _THEME_EXACT_FILES or filename.startswith(_THEME_PREFIXES)
    candidates = (
        (
            pic / "prism_plus" / mapped,
            pic / "circle" / mapped,
            pic / filename,
            pic / mapped,
        )
        if themed
        else (
            pic / filename,
            pic / mapped,
            pic / "prism_plus" / mapped,
            pic / "circle" / mapped,
        )
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return candidates[0]


def _font_path(assets: Path, torus: bool = False) -> Path:
    font = assets / "font"
    names = (
        ("Torus SemiBold.otf", "ResourceHanRoundedCN-Bold.ttf")
        if torus
        else ("ResourceHanRoundedCN-Bold.ttf", "ResourceHanRoundedCN.otf")
    )
    return next((font / name for name in names if (font / name).is_file()), font / names[0])


def _open(path: Path, size: tuple[int, int] | None = None) -> Image.Image:
    with Image.open(path) as source:
        image = source.convert("RGBA")
    if size:
        image = image.resize(size, Image.Resampling.LANCZOS)
    return image


def _optional(
    assets: Path, filename: str, size: tuple[int, int] | None = None
) -> Image.Image | None:
    path = _theme_path(assets, filename)
    if not path.is_file():
        path = _pic_dir(assets) / filename
    return _open(path, size) if path.is_file() else None


def _cover_path(assets: Path, sid: str) -> Path | None:
    try:
        base = str(int(sid) % 10000)
    except (TypeError, ValueError):
        base = sid.lstrip("0") or "0"
    names = (sid, base, base.zfill(4), base.zfill(5), "0")
    for cover_dir in (assets / "mai" / "cover", assets / "cover"):
        for name in names:
            for suffix in (".png", ".jpg", ".jpeg"):
                candidate = cover_dir / f"{name}{suffix}"
                if candidate.is_file():
                    return candidate
    return None


def _cover_urls(song_id: Any) -> tuple[str, ...]:
    try:
        sid = int(song_id)
    except (TypeError, ValueError):
        sid = 0
    return (
        f"https://assets.lxns.net/maimai/jacket/{sid}.png!webp",
        f"https://assets.lxns.net/maimai/jacket/{sid % 10000}.png!webp",
        f"https://www.diving-fish.com/covers/{sid:05d}.png",
    )


def _fetch_image(url: str) -> Image.Image | None:
    if not url:
        return None
    try:
        request = urllib.request.Request(
            url, headers={"User-Agent": "MaiBot/1.0 maimaidx-prober"}
        )
        with urllib.request.urlopen(request, timeout=10) as response:
            data = response.read()
        return Image.open(io.BytesIO(data)).convert("RGBA")
    except Exception:
        return None


def _image_from_data_url(cover_data_url: str) -> Image.Image | None:
    if not cover_data_url or "," not in cover_data_url:
        return None
    try:
        raw = base64.b64decode(cover_data_url.split(",", 1)[1], validate=True)
        return Image.open(io.BytesIO(raw)).convert("RGBA")
    except Exception:
        return None


def _load_cover(
    sid: str,
    cover_data_url: str = "",
    assets: Path = ASSETS_ROOT,
    size: tuple[int, int] | None = None,
) -> Image.Image | None:
    image = _image_from_data_url(cover_data_url)
    if image is not None and size:
        image = image.resize(size, Image.Resampling.LANCZOS)
    if image is not None:
        return image
    local = _cover_path(COVER_ROOT, sid) or _cover_path(assets, sid)
    if local:
        return _open(local, size)
    for url in _cover_urls(sid):
        image = _fetch_image(url)
        if image is not None:
            if size:
                image = image.resize(size, Image.Resampling.LANCZOS)
            return image
    return None


def _display_width(text: str) -> int:
    return sum(
        2 if unicodedata.east_asian_width(char) in {"W", "F", "A"} else 1
        for char in text
    )


def _truncate(text: object, width: int) -> str:
    value = str(text or "")
    if _display_width(value) <= width:
        return value
    result = ""
    for char in value:
        if _display_width(result + char) > width - 3:
            break
        result += char
    return result + "..."


def _rank_name(chart: dict) -> str:
    rate = str(chart.get("rate") or "").strip()
    if rate:
        normalized = rate.lower().replace("＋", "+")
        if normalized == "ss+":
            normalized = "ssp"
        elif normalized == "sss+":
            normalized = "sssp"
        elif normalized == "s+":
            normalized = "sp"
        return RANK_MAP.get(normalized, rate)
    achievement = _f(chart.get("achievement") or chart.get("achievements"))
    for threshold, name in (
        (100.5, "SSSp"),
        (100.0, "SSS"),
        (99.5, "SSp"),
        (99.0, "SS"),
        (98.0, "Sp"),
        (97.0, "S"),
        (94.0, "AAA"),
        (90.0, "AA"),
        (80.0, "A"),
        (75.0, "BBB"),
        (70.0, "BB"),
        (60.0, "B"),
        (50.0, "C"),
    ):
        if achievement >= threshold:
            return name
    return "D"


def _max_dx_score(chart: dict, lookup: dict[str, dict]) -> int:
    music = lookup.get(
        str(chart.get("music_id") or chart.get("song_id") or "")
    )
    index = _i(chart.get("level_index"), -1)
    charts = (music or {}).get("charts") or []
    if not 0 <= index < len(charts):
        return 0
    notes = charts[index].get("notes") or []
    return sum(_i(note) for note in notes) * 3


def _dx_star(score: int, maximum: int) -> int:
    if maximum <= 0:
        return 0
    percentage = score / maximum * 100
    if percentage < 85:
        return 0
    if percentage < 90:
        return 1
    if percentage < 93:
        return 2
    if percentage < 95:
        return 3
    if percentage < 97:
        return 4
    return 5


def _best_rating_values(ds: float) -> list[int]:
    """按 AWMC 模板计算 Expert+ 各评级档的预估 RA（AP 为 100.5 档 + 1）。"""

    if ds <= 0:
        return [0] * 7
    return [
        compute_ra(ds, 100.5) + 1,
        compute_ra(ds, 100.5),
        compute_ra(ds, 100.0),
        compute_ra(ds, 99.5),
        compute_ra(ds, 99.0),
        compute_ra(ds, 98.0),
        compute_ra(ds, 97.0),
    ]


def _placeholder_cover(size: tuple[int, int]) -> Image.Image:
    image = Image.new("RGBA", size, (228, 232, 239, 255))
    draw = ImageDraw.Draw(image)
    draw.rectangle(
        (4, 4, size[0] - 5, size[1] - 5),
        outline=(160, 168, 180),
        width=2,
    )
    return image


def _notes_to_list(notes: Any) -> list[int]:
    if isinstance(notes, dict):
        return [
            _i(notes.get("tap", 0)),
            _i(notes.get("hold", 0)),
            _i(notes.get("slide", 0)),
            _i(notes.get("touch", 0)),
            _i(notes.get("break", 0)),
        ]
    if isinstance(notes, list):
        return [_i(value) for value in notes]
    return []


def _merge_charts(song: dict, extra: dict | None) -> list[dict]:
    """优先使用水鱼 charts；缺失时用落雪 difficulties 补 notes/charter。"""

    charts = [dict(item) for item in (song.get("charts") or []) if isinstance(item, dict)]
    if not charts and (extra or {}).get("difficulties"):
        diffs = extra["difficulties"]
        song_type = str(song.get("type") or "").strip().lower()
        section = (
            "utage"
            if song_type == "utage"
            else ("dx" if song_type == "dx" else "standard")
        )
        for item in diffs.get(section, []) or []:
            if isinstance(item, dict):
                charts.append({
                    "difficulty": item.get("difficulty", 0),
                    "charter": item.get("note_designer", ""),
                    "notes": _notes_to_list(item.get("notes")),
                })
        charts.sort(key=lambda item: _i(item.get("difficulty", 0)))

    lxns_by_level: dict[int, dict] = {}
    for section in ("standard", "dx", "utage"):
        for item in (extra or {}).get("difficulties", {}).get(section, []) or []:
            if isinstance(item, dict):
                lxns_by_level[_i(item.get("difficulty", 0))] = item
    for index, chart in enumerate(charts):
        lxns_item = lxns_by_level.get(index)
        if not lxns_item:
            continue
        chart.setdefault("charter", str(lxns_item.get("note_designer", "") or ""))
        if not chart.get("notes"):
            chart["notes"] = _notes_to_list(lxns_item.get("notes"))
    return charts


def _to_base64(image: Image.Image) -> str:
    output = io.BytesIO()
    image.save(output, format="PNG")
    image.close()
    return base64.b64encode(output.getvalue()).decode()


def _render_song_info_sync(
    song: dict, cover_data_url: str = "", extra: dict | None = None
) -> Image.Image:
    assets = ASSETS_ROOT
    pic = _pic_dir(assets)
    music = dict(song)
    music["basic_info"] = dict(song.get("basic_info") or {})
    if extra and extra.get("genre_name"):
        music["basic_info"]["genre"] = extra["genre_name"]
    music["charts"] = _merge_charts(song, extra)

    template = _theme_path(assets, "chart_info.png")
    image = (
        _open(template)
        if template.is_file()
        else Image.new("RGBA", (1200, 1300), (239, 246, 255, 255))
    )
    if image.size != (1200, 1300):
        image = image.resize((1200, 1300), Image.Resampling.LANCZOS)
    draw = ImageDraw.Draw(image)
    cn = lambda size: ImageFont.truetype(str(_font_path(assets)), size)
    torus = lambda size: ImageFont.truetype(str(_font_path(assets, torus=True)), size)
    color = (124, 129, 255)

    logo = _optional(assets, "logo.png", (249, 120))
    if logo:
        image.alpha_composite(logo, (65, 25))
    info = music.get("basic_info") or {}
    if info.get("is_new"):
        new_song = _optional(assets, "UI_CMN_TabTitle_NewSong.png", (249, 120))
        if new_song:
            image.alpha_composite(new_song, (842, 100))

    sid = _song_id(song)
    cover = _load_cover(sid, cover_data_url, assets, (242, 242))
    image.alpha_composite(
        cover or _placeholder_cover((242, 242)), (133, 197)
    )
    version = str(info.get("from") or info.get("version") or "")
    if version and (pic / f"{version}.png").is_file():
        image.alpha_composite(_open(pic / f"{version}.png", (182, 90)), (800, 370))
    kind = str(music.get("type") or "SD").upper()
    kind_icon = _optional(assets, f"{kind}.png", (80, 30))
    if kind_icon:
        image.alpha_composite(kind_icon, (295, 410))

    draw.text(
        (405, 220),
        _truncate(music.get("title"), 40),
        font=cn(28),
        fill=color,
        anchor="lm",
    )
    draw.text(
        (407, 265),
        _truncate(info.get("artist"), 50),
        font=cn(20),
        fill=color,
        anchor="lm",
    )
    draw.text(
        (460, 345),
        str(info.get("bpm") or "-"),
        font=torus(24),
        fill=color,
        anchor="lm",
    )
    draw.text((405, 435), f"ID {sid}", font=torus(22), fill=color, anchor="lm")
    draw.text(
        (665, 435),
        str(info.get("genre") or "-"),
        font=cn(24),
        fill=color,
        anchor="mm",
    )

    levels = music.get("level") or []
    constants = music.get("ds") or []
    charts = music.get("charts") or []
    for index, chart in enumerate(charts[:5]):
        y = 590 + 70 * index
        level = levels[index] if index < len(levels) else "-"
        constant = constants[index] if index < len(constants) else "-"
        draw.text(
            (120, y), f"{level}({constant})", font=torus(21), fill="white", anchor="mm"
        )
        charter = chart.get("charter") or "-"
        draw.text(
            (310, y),
            _truncate(charter, 19),
            font=cn(19),
            fill=color,
            anchor="mm",
        )
        notes = [_i(value) for value in (chart.get("notes") or [])]
        values: list[Any] = [sum(notes), *notes]
        # 模板固定 6 列：TOTAL/TAP/HOLD/SLIDE/TOUCH/BREAK。
        # 水鱼 notes 只返回 4 项（不含 BREAK），缺失列补在末尾。
        if len(values) < 6:
            values.extend(["-"] * (6 - len(values)))
        for column in range(6):
            value = values[column] if column < len(values) else "-"
            draw.text(
                (480 + 122 * column, y),
                str(value),
                font=torus(23),
                fill=color,
                anchor="mm",
            )
        if index > 1:
            best = _best_rating_values(
                _f(constants[index]) if index < len(constants) else 0.0
            )
            for column, value in enumerate(best):
                draw.text(
                    (295 + 125 * column, 1017 + 46 * (index - 2)),
                    str(value),
                    font=torus(22),
                    fill=color,
                    anchor="mm",
                )

    draw.text((295, 985), "*未实装", font=cn(12), fill=color, anchor="mm")
    draw.text(
        (600, 1220),
        DESIGN_CREDIT,
        font=cn(22),
        fill=color,
        anchor="mm",
        stroke_width=3,
        stroke_fill="white",
    )
    return image.convert("RGB")


def _render_play_info_sync(
    song: dict,
    records: list[dict],
    source_label: str,
    cover_data_url: str = "",
) -> Image.Image:
    assets = ASSETS_ROOT
    pic = _pic_dir(assets)
    music = dict(song)
    music["basic_info"] = dict(song.get("basic_info") or {})
    music["charts"] = _merge_charts(song, None)
    template = _theme_path(assets, "play_info.png")
    image = (
        _open(template)
        if template.is_file()
        else Image.new("RGBA", (1200, 900), (239, 246, 255, 255))
    )
    draw = ImageDraw.Draw(image)
    cn = lambda size: ImageFont.truetype(str(_font_path(assets)), size)
    torus = lambda size: ImageFont.truetype(str(_font_path(assets, torus=True)), size)
    color = (124, 129, 255)
    sid = _song_id(song)
    basic = music.get("basic_info") or {}

    logo = _optional(assets, "logo.png", (249, 120))
    if logo:
        image.alpha_composite(logo, (42, 34))
    cover = _load_cover(sid, cover_data_url, assets, (300, 300))
    image.alpha_composite(
        cover or _placeholder_cover((300, 300)), (100, 260)
    )
    version = str(basic.get("from") or basic.get("version") or "")
    if version and (pic / f"{version}.png").is_file():
        image.alpha_composite(_open(pic / f"{version}.png", (183, 90)), (295, 205))
    kind = str(music.get("type") or "SD").upper()
    kind_icon = _optional(assets, f"{kind}.png", (55, 20))
    if kind_icon:
        image.alpha_composite(kind_icon, (350, 560))

    draw.text(
        (255, 595),
        _truncate(basic.get("artist"), 58),
        font=cn(12),
        fill=color,
        anchor="mm",
    )
    draw.text(
        (255, 622),
        _truncate(music.get("title"), 38),
        font=cn(18),
        fill=color,
        anchor="mm",
    )
    draw.text((160, 720), sid, font=torus(22), fill=color, anchor="mm")
    draw.text(
        (380, 720),
        str(basic.get("bpm") or "-"),
        font=torus(22),
        fill=color,
        anchor="mm",
    )
    draw.text(
        (1120, 70),
        f"数据源：{source_label}",
        font=cn(18),
        fill=color,
        anchor="rm",
        stroke_width=2,
        stroke_fill="white",
    )

    levels = music.get("level") or []
    constants = music.get("ds") or []
    music_charts = music.get("charts") or []
    by_level = {
        _i(record.get("level_index"), -1): record
        for record in records
        if isinstance(record, dict)
    }
    lookup = {sid: music}
    row_count = min(max(len(levels), len(music_charts), 4), 5)
    for index in range(row_count):
        row_y = 235 + 100 * index
        d_icon = _optional(assets, f"d_{index}.png")
        if d_icon:
            image.alpha_composite(d_icon, (650, row_y))
        ds = _f(constants[index]) if index < len(constants) else 0.0
        draw.text(
            (685, 248 + 100 * index),
            f"{ds:.1f}",
            font=torus(20),
            fill=color,
            anchor="mm",
        )
        record = by_level.get(index)
        if not record:
            draw.text(
                (800, 302 + 100 * index),
                "未游玩",
                font=cn(30),
                fill=color,
                anchor="mm",
            )
            continue

        ra_dx = _optional(assets, "ra_dx.png", (102, 44))
        if ra_dx:
            image.alpha_composite(ra_dx, (850, 272 + 100 * index))
        rank = _optional(
            assets,
            f"UI_TTR_Rank_{_rank_name(record)}.png",
            (100, 45),
        )
        if rank:
            image.alpha_composite(rank, (737, 272 + 100 * index))
        fcfs = _optional(assets, "fcfs.png")
        if fcfs:
            image.alpha_composite(fcfs, (965, 265 + 100 * index))

        fc_key = FC_MAP.get(str(record.get("fc") or "").casefold())
        if fc_key:
            fc = _optional(assets, f"UI_CHR_PlayBonus_{fc_key}.png", (65, 65))
            if fc is None:
                fc = _optional(assets, f"UI_MSS_MBase_Icon_{fc_key}.png", (55, 55))
            if fc:
                image.alpha_composite(fc, (960, 261 + 100 * index))
        fs_key = FS_MAP.get(str(record.get("fs") or "").casefold())
        if fs_key:
            fs_icon = _optional(assets, f"UI_CHR_PlayBonus_{fs_key}.png", (65, 65))
            if fs_icon is None:
                fs_icon = _optional(assets, f"UI_MSS_MBase_Icon_{fs_key}.png", (55, 55))
            if fs_icon:
                image.alpha_composite(fs_icon, (1025, 261 + 100 * index))

        maximum = _max_dx_score(record, lookup)
        dx_score = _i(record.get("dxScore") or record.get("dx_score"))
        star = _dx_star(dx_score, maximum)
        if star:
            star_icon = _optional(
                assets, f"UI_GAM_Gauge_DXScoreIcon_0{star}.png", (32, 19)
            )
            if star_icon:
                image.alpha_composite(star_icon, (851, 296 + 100 * index))
        draw.text(
            (916, 304 + 100 * index),
            f"{dx_score}/{maximum}",
            font=torus(13),
            fill=color,
            anchor="mm",
        )
        achievement = _f(record.get("achievement") or record.get("achievements"))
        draw.text(
            (500, 295 + 100 * index),
            f"{achievement:.4f}%",
            font=torus(30),
            fill=color,
            anchor="lm",
        )
        draw.text(
            (915, 283 + 100 * index),
            str(_i(record.get("ra"))),
            font=torus(18),
            fill=color,
            anchor="mm",
        )

    footer_size = 18
    while (
        footer_size > 10
        and draw.textlength(DESIGN_CREDIT, font=cn(footer_size)) > image.width - 80
    ):
        footer_size -= 1
    draw.text(
        (image.width // 2, image.height - 22),
        DESIGN_CREDIT,
        font=cn(footer_size),
        fill=color,
        anchor="mm",
        stroke_width=3,
        stroke_fill="white",
    )
    return image.convert("RGB")


async def render_song_info(
    song: dict, cover_data_url: str = "", extra: dict | None = None
) -> str:
    """渲染单曲信息为 base64 PNG（AWMC chart_info 模板）。"""

    image = await asyncio.to_thread(
        _render_song_info_sync, song, cover_data_url, extra
    )
    return _to_base64(image)


async def render_play_info(
    song: dict,
    records: list[dict],
    source_label: str,
    cover_data_url: str = "",
) -> str:
    """渲染个人单曲游玩信息为 base64 PNG（AWMC play_info 模板）。"""

    image = await asyncio.to_thread(
        _render_play_info_sync, song, records, source_label, cover_data_url
    )
    return _to_base64(image)
