# -*- coding: utf-8 -*-
"""AWMC / Yuzu 原版 B50 渲染。

直接复用 Yuri-YuzuChaN / BlueDeer233 版式的固定画布、成绩卡与 UI 贴图，
素材来自 Resource CN1.55 static 包（assets/awmc/）。
本渲染器只供 B50 / AP50 使用，其它信息查询仍使用 theme.panel_style()。
"""

from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any, Optional

from PIL import Image, ImageDraw, ImageFont

import asyncio
import base64
import concurrent.futures
import functools
import io
import random
import unicodedata
import urllib.request

from ..constants import DIFF_RGBA
from ..services.covers import sniff_mime
from ..services.renderer import HtmlRenderer

from .difficulty_palette import apply_difficulty_palette

ASSETS_ROOT = Path(__file__).resolve().parent.parent.parent / "assets" / "awmc_core"
COVER_ROOT = Path(__file__).resolve().parent.parent.parent / "assets" / "awmc" / "mai" / "cover"

DESIGN_CREDIT = (
    "Designed by Yuri-YuzuChaN & BlueDeer233 | Generated by MaiBot"
)
CARD_ASSETS = (
    "b50_score_basic.png",
    "b50_score_advanced.png",
    "b50_score_expert.png",
    "b50_score_master.png",
    "b50_score_remaster.png",
)
DEFAULT_AVATARS = (
    "UI_Icon_509506.png",
    "default_avatars/lxbot.webp",
    "default_avatars/salt.webp",
    "default_avatars/reisasol.webp",
    "default_avatars/icon-512.png",
)
YEAR_IN_REVIEW_FOOTER = "year_in_review_footer.webp"

RANK_MAP = {
    "d": "D", "c": "C", "b": "B", "bb": "BB", "bbb": "BBB",
    "a": "A", "aa": "AA", "aaa": "AAA",
    "s": "S", "sp": "Sp", "ss": "SS", "ssp": "SSp",
    "sss": "SSS", "sssp": "SSSp",
}
FC_MAP = {
    "fc": "FC", "fcp": "FCp", "fc+": "FCp",
    "ap": "AP", "app": "APp", "ap+": "APp",
}
FS_MAP = {
    "fs": "FS", "fsp": "FSp", "fs+": "FSp",
    "fsd": "FSD", "fsdp": "FSDp", "fsd+": "FSDp",
    "sync": "Sync",
}
ID_COLORS = DIFF_RGBA


def _f(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _i(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _display_width(text: str) -> int:
    return sum(
        2 if unicodedata.east_asian_width(char) in {"W", "F", "A"} else 1
        for char in text
    )


def _truncate(text: object, width: int) -> str:
    value = str(text or "")
    if _display_width(value) <= width:
        return value
    result = ""
    for char in value:
        if _display_width(result + char) > width - 3:
            break
        result += char
    return result + "..."


def _rank_name(chart: dict) -> str:
    rate = str(chart.get("rate") or "").strip()
    if rate:
        normalized = rate.lower().replace("＋", "+")
        if normalized == "ss+":
            normalized = "ssp"
        elif normalized == "sss+":
            normalized = "sssp"
        elif normalized == "s+":
            normalized = "sp"
        return RANK_MAP.get(normalized, rate)
    achievement = _f(chart.get("achievement") or chart.get("achievements"))
    for threshold, name in (
        (100.5, "SSSp"), (100.0, "SSS"), (99.5, "SSp"), (99.0, "SS"),
        (98.0, "Sp"), (97.0, "S"), (94.0, "AAA"), (90.0, "AA"),
        (80.0, "A"), (75.0, "BBB"), (70.0, "BB"), (60.0, "B"),
        (50.0, "C"),
    ):
        if achievement >= threshold:
            return name
    return "D"


def _rating_asset(rating: int) -> str:
    for threshold, name in (
        (1000, "01"), (2000, "02"), (4000, "03"), (7000, "04"),
        (10000, "05"), (12000, "06"), (13000, "07"),
        (14000, "08"), (14500, "09"), (15000, "10"),
    ):
        if rating < threshold:
            return f"UI_CMN_DXRating_{name}.png"
    return "UI_CMN_DXRating_11.png"


def _dx_star(dx_score: int, maximum: int) -> int:
    if maximum <= 0:
        return 0
    percentage = dx_score / maximum * 100
    if percentage <= 85:
        return 0
    if percentage <= 90:
        return 1
    if percentage <= 93:
        return 2
    if percentage <= 95:
        return 3
    if percentage <= 97:
        return 4
    return 5


def _open(path: Path, size: tuple[int, int] | None = None) -> Image.Image:
    with Image.open(path) as source:
        image = source.convert("RGBA")
    image = apply_difficulty_palette(image, path.name)
    if size:
        image = image.resize(size, Image.Resampling.LANCZOS)
    return image


@functools.lru_cache(maxsize=1)
def _simple_gradient_background() -> Image.Image:
    """生成 1400x1600 的简洁渐变背景（不含装饰元素）。"""

    size = (1400, 1600)
    grid_size = (96, 96)
    top_left = (92, 205, 248)
    top_right = (183, 171, 250)
    bottom_left = (118, 226, 234)
    bottom_right = (242, 157, 218)

    def _mix(
        c1: tuple[int, int, int], c2: tuple[int, int, int], t: float
    ) -> tuple[int, int, int]:
        return tuple(int(a + (b - a) * t) for a, b in zip(c1, c2))

    grid = Image.new("RGB", grid_size)
    for y in range(grid_size[1]):
        ty = y / (grid_size[1] - 1)
        for x in range(grid_size[0]):
            tx = x / (grid_size[0] - 1)
            top = _mix(top_left, top_right, tx)
            bottom = _mix(bottom_left, bottom_right, tx)
            grid.putpixel((x, y), _mix(top, bottom, ty))
    grid = grid.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
    return grid.resize(size, Image.Resampling.BICUBIC).convert("RGBA")


def _theme_path(assets: Path, filename: str) -> Path:
    pic = assets / "mai" / "pic"
    filename = "b50.png" if filename == "b50_bg.png" else filename
    themed = (
        filename in {"b50.png", "logo.png"}
        or filename.startswith(("UI_TTR_Rank_", "UI_CMN_DXRating_"))
    )
    candidates = (
        (pic / "prism_plus" / filename, pic / "circle" / filename, pic / filename)
        if themed
        else (pic / filename, pic / "prism_plus" / filename, pic / "circle" / filename)
    )
    return next((path for path in candidates if path.is_file()), candidates[0])


def _font_path(assets: Path, torus: bool = False) -> Path:
    font = assets / "font"
    names = (
        ("Torus SemiBold.otf", "ResourceHanRoundedCN-Bold.ttf")
        if torus
        else ("ResourceHanRoundedCN-Bold.ttf", "ResourceHanRoundedCN.otf")
    )
    return next(
        (font / name for name in names if (font / name).is_file()),
        font / names[0],
    )


def _optional(
    assets: Path, filename: str, size: tuple[int, int] | None = None
) -> Image.Image | None:
    path = _theme_path(assets, filename)
    return _open(path, size) if path.is_file() else None


def _random_default_avatar(assets: Path) -> Image.Image:
    """随机选择一个默认头像；缺失候选时回退原始游戏默认图标。"""

    pic = assets / "mai" / "pic"
    candidates = [
        pic / name
        for name in DEFAULT_AVATARS
        if (pic / name).is_file()
    ]
    if not candidates:
        candidates = [pic / "UI_Icon_509506.png"]
    return _open(random.choice(candidates), (120, 120))


def _placeholder_cover(size: tuple[int, int]) -> Image.Image:
    image = Image.new("RGBA", size, (205, 180, 240, 255))
    draw = ImageDraw.Draw(image)
    try:
        font = ImageFont.truetype("arial.ttf", 32)
    except OSError:
        font = ImageFont.load_default()
    draw.text(
        (size[0] / 2, size[1] / 2),
        "♪",
        fill=(255, 255, 255, 210),
        anchor="mm",
        font=font,
    )
    return image


def _image_from_bytes(data: bytes) -> Image.Image | None:
    if sniff_mime(data) is None:
        return None
    try:
        with Image.open(io.BytesIO(data)) as source:
            return source.convert("RGBA")
    except Exception:
        return None


def _image_from_data_url(data_url: str) -> Image.Image | None:
    if not data_url or "," not in data_url:
        return None
    try:
        return _image_from_bytes(
            base64.b64decode(data_url.split(",", 1)[1], validate=True)
        )
    except Exception:
        return None


def _fetch_image(url: str) -> Image.Image | None:
    if not url:
        return None
    try:
        request = urllib.request.Request(
            url, headers={"User-Agent": "MaiBot/1.0 maimaidx-prober"}
        )
        with urllib.request.urlopen(request, timeout=10) as response:
            data = response.read()
        return _image_from_bytes(data)
    except Exception:
        return None


def _df_cover_id(song_id: Any) -> str:
    try:
        sid = int(song_id)
    except (TypeError, ValueError):
        return str(song_id or "").zfill(5)
    if 10001 <= sid <= 11000:
        sid -= 10000
    return str(sid).zfill(5)


def _cover_resource_ids(song_id: Any) -> tuple[str, ...]:
    try:
        sid = int(song_id)
    except (TypeError, ValueError):
        sid = 0
    base = sid % 10000
    return (
        str(sid),
        str(base),
        str(base).zfill(4),
        str(base).zfill(5),
        _df_cover_id(song_id),
    )


def _cover_path(assets: Path, sid: str) -> Path | None:
    for cover_dir in (
        COVER_ROOT,
        assets / "mai" / "cover",
        assets / "cover",
        ASSETS_ROOT / "mai" / "cover",
        ASSETS_ROOT / "cover",
    ):
        for name in _cover_resource_ids(sid):
            for suffix in (".png", ".jpg", ".jpeg", ".webp"):
                candidate = cover_dir / f"{name}{suffix}"
                if candidate.is_file():
                    return candidate
    return None


def _cover_urls(song_id: Any) -> tuple[str, ...]:
    try:
        sid = int(song_id)
    except (TypeError, ValueError):
        sid = 0
    lxns_resource_id = sid % 10000
    return (
        f"https://assets.lxns.net/maimai/jacket/{lxns_resource_id}.png!webp",
        f"https://assets2.lxns.net/maimai/jacket/{lxns_resource_id}.png",
        f"https://www.diving-fish.com/covers/{_df_cover_id(song_id)}.png",
    )


def _record_cover_key(item: dict) -> str:
    return str(
        item.get("df_song_id")
        or item.get("music_id")
        or item.get("song_id")
        or item.get("id")
        or ""
    )


async def _prefetch_cover_data_urls(
    sd: list[dict],
    dx: list[dict],
    cover_fetcher: Optional[Callable[[str], Awaitable[Optional[str]]]],
) -> dict[str, str]:
    if cover_fetcher is None:
        return {}
    keys = []
    for item in (*sd, *dx):
        sid = _record_cover_key(item)
        if sid and sid not in keys:
            keys.append(sid)
    results = await asyncio.gather(
        *(cover_fetcher(sid) for sid in keys),
        return_exceptions=True,
    )
    return {
        sid: data_url
        for sid, data_url in zip(keys, results)
        if isinstance(data_url, str) and data_url
    }


async def _empty_data_url() -> str:
    return ""


def _load_covers(
    sd: list[dict],
    dx: list[dict],
    cover_data_urls: dict[str, str] | None = None,
) -> dict[str, Image.Image]:
    result: dict[str, Image.Image] = {}
    missing: list[str] = []
    cover_data_urls = cover_data_urls or {}
    for item in (*sd, *dx):
        sid = _record_cover_key(item)
        if sid and sid in result:
            continue
        if not sid:
            continue
        image = _image_from_data_url(cover_data_urls.get(sid, ""))
        if image is not None:
            result[sid] = image
            continue
        local = _cover_path(ASSETS_ROOT, sid)
        if local:
            image = _open(local)
            result[sid] = image
        else:
            missing.append(sid)
    if missing:
        with concurrent.futures.ThreadPoolExecutor(
            max_workers=min(8, len(missing))
        ) as pool:
            futures = {
                pool.submit(_remote_cover, sid): sid
                for sid in missing
            }
            for future in concurrent.futures.as_completed(futures):
                sid = futures[future]
                image = future.result()
                if image is not None:
                    result[sid] = image
    return result


def _remote_cover(sid: str) -> Image.Image | None:
    return next(
        (
            loaded
            for loaded in (_fetch_image(url) for url in _cover_urls(sid))
            if loaded is not None
        ),
        None,
    )


def _load_avatar(url: str, avatar_data_url: str = "") -> Image.Image | None:
    return _image_from_data_url(avatar_data_url) or _fetch_image(url)


class AWMCRenderer:
    def __init__(
        self,
        context: dict,
        assets_path: Path,
        covers: dict[str, Image.Image] | None = None,
        avatar: Image.Image | None = None,
    ) -> None:
        self.context = context
        self.assets = assets_path
        self.covers = covers or {}
        self.avatar = avatar

        self.image = _simple_gradient_background().copy()
        self.draw = ImageDraw.Draw(self.image)
        self.cn_fonts: dict[int, ImageFont.FreeTypeFont] = {}
        self.torus_fonts: dict[int, ImageFont.FreeTypeFont] = {}
        self.cards = [_open(_theme_path(self.assets, name)) for name in CARD_ASSETS]

    def font(self, size: int, torus: bool = False) -> ImageFont.FreeTypeFont:
        cache = self.torus_fonts if torus else self.cn_fonts
        if size not in cache:
            cache[size] = ImageFont.truetype(
                str(_font_path(self.assets, torus)), size
            )
        return cache[size]

    def text(
        self,
        xy: tuple[int, int],
        value: object,
        size: int,
        fill: Any,
        anchor: str = "la",
        *,
        torus: bool = False,
        stroke: int = 0,
        stroke_fill: Any = None,
    ) -> None:
        self.draw.text(
            xy,
            str(value),
            font=self.font(size, torus),
            fill=fill,
            anchor=anchor,
            stroke_width=stroke,
            stroke_fill=stroke_fill,
        )

    def _paste_optional(
        self, filename: str, size: tuple[int, int] | None, xy: tuple[int, int]
    ) -> None:
        image = _optional(self.assets, filename, size)
        if image is not None:
            self.image.alpha_composite(image, xy)

    def _header(self, source_label: str) -> None:
        player = self.context.get("player") or {}
        rating = _i(player.get("rating"))
        self._paste_optional("logo.png", (249, 120), (14, 60))
        self._paste_optional("UI_Plate_550101.png", (800, 130), (300, 60))
        if source_label == "落雪":
            footer = _optional(self.assets, YEAR_IN_REVIEW_FOOTER, (180, 180))
            if footer is not None:
                self.image.alpha_composite(footer, (1160, 45))

        if self.avatar is not None:
            self.image.alpha_composite(self.avatar.resize((120, 120)), (305, 65))
        else:
            self.image.alpha_composite(
                _random_default_avatar(self.assets), (305, 65)
            )

        self._paste_optional(_rating_asset(rating), (186, 35), (435, 72))
        digits_ok = True
        digits: list[Image.Image] = []
        for digit in f"{rating:05d}":
            image = _optional(
                self.assets, f"UI_NUM_Drating_{digit}.png", (17, 20)
            )
            if image is None:
                digits_ok = False
                break
            digits.append(image)
        if digits_ok:
            for index, image in enumerate(digits):
                self.image.alpha_composite(image, (520 + 15 * index, 80))
        else:
            self.text(
                (520, 80), f"{rating:05d}", 19, "white",
                torus=True, stroke=2, stroke_fill="#39405a",
            )

        self._paste_optional("Name.png", None, (435, 115))
        # 段位/阶级数据缺失（如水鱼来源）时不贴徽章，避免显示误导性的「初段/阶级0」
        if player.get("additional_rating") is not None:
            course = _i(player.get("additional_rating"))
            course_number = course if course <= 10 else course + 1
            course_number = max(0, min(course_number, 23))
            self._paste_optional(
                f"UI_DNM_DaniPlate_{course_number:02d}.png", (80, 32), (625, 120)
            )
        if player.get("class_rank") is not None:
            class_rank = _i(player.get("class_rank"))
            class_name = f"UI_FBR_Class_{max(0, min(class_rank, 25)):02d}.png"
            self._paste_optional(class_name, (90, 54), (620, 60))
        self._paste_optional("UI_CMN_Shougou_Rainbow.png", (270, 27), (435, 160))

        self.text(
            (445, 135), _truncate(player.get("nickname"), 22), 25,
            "black", "lm",
        )
        summary = self.context.get("summary") or {}
        b35 = _i(summary.get("b35_ra"))
        b15 = _i(summary.get("b15_ra"))
        self.text(
            (570, 172),
            f"B35: {b35} + B15: {b15} = {rating}",
            17, "black", "mm", stroke=3, stroke_fill="white",
        )
        self.text(
            (570, 198), f"数据源：{source_label}", 14, (70, 70, 70),
            "mm", stroke=2, stroke_fill=(255, 255, 255, 220),
        )
        self.text(
            (700, 1570), DESIGN_CREDIT, 23, (124, 129, 255),
            "mm", stroke=4, stroke_fill="white",
        )

    def _card(self, chart: dict, x: int, y: int) -> None:
        index = max(0, min(_i(chart.get("level_index"), 3), 4))
        self.image.alpha_composite(self.cards[index], (x, y))
        sid = _record_cover_key(chart)
        cover = self.covers.get(sid) or _placeholder_cover((75, 75))
        self.image.alpha_composite(cover.resize((75, 75)), (x + 12, y + 12))

        kind = str(chart.get("type") or "SD").upper()
        self._paste_optional(f"{kind}.png", (37, 14), (x + 51, y + 91))
        rank = _optional(
            self.assets, f"UI_TTR_Rank_{_rank_name(chart)}.png", (63, 28)
        )
        if rank is not None:
            self.image.alpha_composite(rank, (x + 92, y + 78))

        fc_key = FC_MAP.get(str(chart.get("fc") or "").strip().lower())
        if fc_key:
            self._paste_optional(
                f"UI_MSS_MBase_Icon_{fc_key}.png", (34, 34), (x + 154, y + 77)
            )
        fs_key = FS_MAP.get(str(chart.get("fs") or "").strip().lower())
        if fs_key:
            self._paste_optional(
                f"UI_MSS_MBase_Icon_{fs_key}.png", (34, 34), (x + 185, y + 77)
            )

        dx_star = _i(chart.get("dx_star"))
        if not dx_star:
            maximum = _i(chart.get("maximum") or chart.get("max_dx_score"))
            if maximum > 0:
                dx_star = _dx_star(
                    _i(chart.get("dx_score") or chart.get("dxScore")), maximum
                )
        if 1 <= dx_star <= 5:
            self._paste_optional(
                f"UI_GAM_Gauge_DXScoreIcon_0{dx_star}.png", (47, 26),
                (x + 217, y + 80),
            )

        self.text((x + 26, y + 98), sid, 13, ID_COLORS[index], "mm", torus=True)
        self.text(
            (x + 93, y + 14), _truncate(chart.get("title"), 18), 14,
            "white", "lm",
        )
        achievement = _f(chart.get("achievement") or chart.get("achievements"))
        self.text((x + 93, y + 38), f"{achievement:.4f}%", 30, "white", "lm", torus=True)
        self.text(
            (x + 93, y + 65),
            f"{_f(chart.get('ds')):.1f} -> {_i(chart.get('ra'))}",
            15, "white", "lm", torus=True,
        )
        dx_score = _i(chart.get("dx_score") or chart.get("dxScore"))
        maximum = _i(chart.get("maximum") or chart.get("max_dx_score"))
        if maximum > 0:
            self.text(
                (x + 219, y + 65), f"{dx_score}/{maximum}", 15,
                "white", "mm", torus=True,
            )

    def render(self) -> Image.Image:
        self._header(str(self.context.get("source_label") or "maimai"))
        charts = self.context.get("b50") or []
        b35 = [item for item in charts if item.get("bucket") == "B35"][:35]
        b15 = [item for item in charts if item.get("bucket") == "B15"][:15]
        if not b35 and not b15:
            b35, b15 = charts[:35], charts[35:50]
        for start_y, group in ((235, b35), (1085, b15)):
            for number, chart in enumerate(group):
                x = 16 + 276 * (number % 5)
                y = start_y + 114 * (number // 5)
                self._card(chart, x, y)
        return self.image.convert("RGB")


def _build_context(
    charts: dict,
    username: str,
    nickname: str,
    rating: int,
    course_rank: Any,
    class_rank: Any,
    source: str,
) -> dict:
    sd = charts.get("sd") or []
    dx = charts.get("dx") or []
    records = []
    for item in sd:
        record = {**item, "bucket": "B35"}
        if "song_id" not in record:
            record["song_id"] = record.get("music_id")
        records.append(record)
    for item in dx:
        record = {**item, "bucket": "B15"}
        if "song_id" not in record:
            record["song_id"] = record.get("music_id")
        records.append(record)
    return {
        "player": {
            "nickname": nickname,
            "rating": rating,
            "additional_rating": course_rank,
            "class_rank": class_rank,
        },
        "summary": {
            "b35_ra": sum(_i(r.get("ra")) for r in sd),
            "b15_ra": sum(_i(r.get("ra")) for r in dx),
        },
        "b50": records,
        "source_label": "落雪" if source == "lxns" else "水鱼",
    }


async def render_b50(
    renderer: HtmlRenderer,
    charts: dict,
    username: str,
    nickname: str,
    rating: int,
    avatar_url: str = "",
    course_rank: Any = None,
    class_rank: Any = None,
    source: str = "",
    cover_fetcher: Optional[Callable[[str], Awaitable[Optional[str]]]] = None,
    avatar_fetcher: Optional[Callable[[str], Awaitable[Optional[str]]]] = None,
) -> str:
    """使用 AWMC/Yuzu 原始贴图渲染 B50。"""
    del renderer
    sd = charts.get("sd") or []
    dx = charts.get("dx") or []
    cover_data_urls, avatar_data_url = await asyncio.gather(
        _prefetch_cover_data_urls(sd, dx, cover_fetcher),
        (
            avatar_fetcher(avatar_url)
            if avatar_fetcher and avatar_url
            else _empty_data_url()
        ),
    )
    covers, avatar = await asyncio.gather(
        asyncio.to_thread(_load_covers, sd, dx, cover_data_urls),
        asyncio.to_thread(_load_avatar, avatar_url, avatar_data_url),
    )
    context = _build_context(
        charts, username, nickname, rating, course_rank, class_rank, source
    )
    image = await asyncio.to_thread(
        lambda: AWMCRenderer(context, ASSETS_ROOT, covers, avatar).render()
    )
    output = io.BytesIO()
    image.save(output, format="PNG")
    return base64.b64encode(output.getvalue()).decode()
